config/routes.rb
Rails.application.routes.draw do

  
 root 'users#index'
 
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :firstname, presence:true, length:{minimum:3,maximum:12}
    validates :lastname, presence:true, length:{minimun:3,maximum:20}
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index
   @users = User.all
  end
  
  def new
     @user = User.new
  end
 
   def edit
    @user = User.find(params[:id])
   end
  
  def create
   @user = User.new(user_params)
   if @user.save
    flash[:notice] = "User was succesfully created"
    redirect_to user_path(@user)
    else
     render 'new'
   end
  end
   
   
  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was succesfully updated"
      redirect_to user_path(@user)
       else
        render 'edit'
     
    end
  end
  
  def destroy
   @user = User.find(params[:id])
   @user.destroy
   flash[:notice] = "User was succesfully deleted"
   redirect_to users_path
   
  end
  
  def show
   @user = User.find(params[:id])
   
  end 
    
end


 private 
  def user_params
    params.require(:user).permit(:firstname, :lastname,:email) 
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudEval</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>

<ul>

<li><%= msg %></li>

</ul>

<% end %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit existing user</h1>

<% if @user.errors.any? %>

<h2>The following errors prevented the user from getting edited</h2>

<ul>

<% @user.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>

<%= form_for @user do |f| %>

<p>

<%= f.label :firstname %><br/>

<%= f.text_field :firstname %>

</p>

<p>

<%= f.label :lastname %><br/>

<%= f.text_field:lastname %>

</p>

<p>

<%= f.label :email %><br/>

<%= f.text_field:email %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

<%= link_to "Back to users listing", users_path %>

app/views/users/index.html.erb
<h1> Users</h1>

<p>

<%= link_to "Create new user", new_user_path %>

</p>

<table>

<tr>

<th>First Name</th>

<th>Last Name</th>

<th>Email</th>

</tr>

<% @users.each do |user| %>

<tr>

<td><%= user.firstname %></td>

<td><%= user.lastname %></td>

<td><%= user.email %></td>

<td><%= link_to 'Edit', edit_user_path(user) %></td>


<td><%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></td>

</tr>

<% end %>

</table>

app/views/users/new.html.erb
<% if @user.errors.any? %>

<h2>The following errors prevented the user from getting created</h2>

<ul>

<% @user.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>

<h1>Create an user</h1>

<%= form_for @user do |f| %>

<p>

<%= f.label :firstname %><br/>

<%= f.text_field :firstname %>

</p>

<p>

<%= f.label :lastname %><br/>

<%= f.text_field:lastname %>

</p>

<p>

<%= f.label :email %><br/>

<%= f.text_field:email %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

<%= link_to "Back to users listing", users_path %>

app/views/users/show.html.erb
<h1>Showing selected user</h1>

<p>

First name: <%= @user.firstname %>

</p>

<p>

Last name: <%= @user.lastname %>

</p>

<p>

Email: <%= @user.email %>

</p>

<%= link_to "Edit user", edit_user_path(@user) %> |

<%= link_to "Back to users listing", users_path %>